# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_code.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='response_code.proto',
  package='line',
  serialized_pb='\n\x13response_code.proto\x12\x04line*W\n\rRESPONSE_CODE\x12\x06\n\x02OK\x10\x00\x12\x16\n\x12\x45RR_NOT_FOUND_USER\x10\x65\x12\x16\n\x12\x45RR_WROND_PASSWORD\x10\x66\x12\x0e\n\nERR_SYSTEM\x10g')

_RESPONSE_CODE = _descriptor.EnumDescriptor(
  name='RESPONSE_CODE',
  full_name='line.RESPONSE_CODE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERR_NOT_FOUND_USER', index=1, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERR_WROND_PASSWORD', index=2, number=102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERR_SYSTEM', index=3, number=103,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=29,
  serialized_end=116,
)

RESPONSE_CODE = enum_type_wrapper.EnumTypeWrapper(_RESPONSE_CODE)
OK = 0
ERR_NOT_FOUND_USER = 101
ERR_WROND_PASSWORD = 102
ERR_SYSTEM = 103




# @@protoc_insertion_point(module_scope)
